### PR TITLE
Fix mkdocs>=1.1.1 compatibility

### LINKED ISSUE #15: Incompatible with mkdocs version 1.1.1
https://github.com/mkdocs/mkdocs/commit/7b68f7b828f29dffe2603117660bb9442d9348a3

The commit above breaks integrations between this library and mkdocs. 

Pretty sure it would be fixed by updating this line
https://github.com/spotify/mkdocs-monorepo-plugin/blob/master/mkdocs_monorepo_plugin/plugin.py#L54

to include kwargs. thoughts?

### PR DESCRIPTION
**Pull request by rossmechanic**
Fixes #15

### CODE REVIEW

**Comment by emmaindal** [comment]
Cool! Thank you! A few more things:

* Bump up the mkdocs version in /requirements.txt. Would be good to cover that in this PR as well.
* Version change. Bump up the version in /setup.py and add a comment in docs/CHANGELOG.md about the change.

**Comment by emmaindal** [comment]
cc @bih to take a look on this as well!

**Comment by rossmechanic** [comment]
@bih thanks! When do you think this'll be released?

**Comment by bih** [comment]
@rossmechanic It already is :)

**Comment by rossmechanic** [comment]
@bih legend! thanks!

**Pull request merged**
